In [1]:
import torch

In [2]:
# Create an empty tensor

In [3]:
# This is an example where it is like a 1-D Vector with three elements
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [4]:
# This is an example where it is like a 2-D Vector with three elements
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# Create an empty tensor with random values

In [6]:
# This is an example where it is like a 1-D Vector with three elements
x = torch.rand(1,3)
print(x)
print(x.dtype)

tensor([[0.0904, 0.9782, 0.1432]])
torch.float32


In [7]:
# Explicitly give the datatype
x = torch.rand(1,3, dtype=torch.float16)
print(x)

tensor([[0.4395, 0.3682, 0.2910]], dtype=torch.float16)


In [8]:
# To check the size, we can use .size() fn

x = torch.rand(1,3, dtype=torch.float16)
print(x.size())

torch.Size([1, 3])


In [9]:
# Basic Operations on tensors

x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

z = x + y 
z = torch.add(x,y)
# Print the element-wise sum of the tensors
print(z)

tensor([[0.0047, 0.8615],
        [0.8409, 0.0566]])
tensor([[0.0397, 0.6528],
        [0.1546, 0.5224]])
tensor([[0.0445, 1.5143],
        [0.9955, 0.5790]])


In [10]:
# Inplace operation in PyTorch

x = torch.rand(2,2)
y = torch.rand(2,2)

y.add_(x)
print(y)

tensor([[1.0180, 0.9665],
        [1.1324, 0.4965]])


In [11]:
z = x - y
z = torch.sub(x,y)

print(z)

tensor([[-0.7600, -0.3956],
        [-0.2297, -0.3408]])


In [12]:
# Slicing operation 

x = torch.rand(5,3)
print(x)
print(x[:, 0])

tensor([[0.0378, 0.7502, 0.0262],
        [0.3265, 0.7611, 0.3647],
        [0.2618, 0.7322, 0.8101],
        [0.5699, 0.0254, 0.9979],
        [0.1576, 0.9888, 0.5558]])
tensor([0.0378, 0.3265, 0.2618, 0.5699, 0.1576])


In [28]:
# Reshape the tensor

x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

y = x.view(-1,8)
print(y.size())

tensor([[0.8974, 0.1535, 0.4705, 0.7434],
        [0.2420, 0.9783, 0.2768, 0.7144],
        [0.5032, 0.8006, 0.8530, 0.2089],
        [0.0646, 0.4043, 0.1246, 0.4139]])
tensor([0.8974, 0.1535, 0.4705, 0.7434, 0.2420, 0.9783, 0.2768, 0.7144, 0.5032,
        0.8006, 0.8530, 0.2089, 0.0646, 0.4043, 0.1246, 0.4139])
torch.Size([2, 8])


In [38]:
# Converting from numpy to torch tensor or vice versa

import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [42]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [46]:
# CUDA and how to create tensor on GPU

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y 
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [48]:
# Requires grad functionality 

x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
